# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SegmentOrderAheadDemo (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SegmentOrderAheadDemo (iOS)
  pod 'RadarSDK', '~> 3.1'
  pod 'Analytics', '~> 4.1'

end
